project_id = "piynzvpnurnvbrmkyneo"

[functions.upload-pdf]
verify_jwt = false

[functions.get-next-analysis-cost]
verify_jwt = true

[functions.create-payment-session]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false