// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vhgdwravbfkzphhbppma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZoZ2R3cmF2YmZrenBoaGJwcG1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3Mjc3OTEsImV4cCI6MjA1NTMwMzc5MX0.WCfnYJS-dHYk7oAl0ALPzfv3owTvx5CTFnYgHGs5u4k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});